camunda/c8-multi-region

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/kubectl/helpers.go
- test/multi_region_aws_operational_procedure_test.go
- fixes helm upgrade version issue
- remove test to contain 1 for elasticsearch backups, simply rely that the name exists
- add wait for namespace removal as otherwise might end up being a race condition.
> fix(test): explicity set the version on upgrade

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/helpers.go
- test/multi_region_aws_operational_procedure_test.go
- Introduces an env var that allows overwriting the global image tag to overwrite the one of the helm chart.
- Add GHA run for C8.5 and SNAPSHOT
Triggered text execution: https://github.com/camunda/c8-multi-region/actions/runs/8570017263
Also tried it out locally to make sure it works.
Definitely, next up is to parallelise everything and split up the test cases as outlined in - https://github.com/camunda/team-infrastructure-experience/issues/179
> chore(test): allow overwriting global tag via env var

- .github/workflows/nightly_aws_operational_procedure.yml
- aws/dual-region/kubernetes/camunda-values.yml
- aws/dual-region/scripts/export_environment_prerequisites.sh
Helm chart 10.0.2 hopefully removes the requirement for the temporary fixes
gRPC endpoint was off, keycloak and postgres were deployed by default with identity off
bitnami chart destroyed initScript functionaility
> chore(helm): bump to 10.0.1 chart and various temp fixes

- .github/actions/setup-aws/action.yml
- .github/renovate.json5
- .github/workflows/nightly_aws_operational_procedure.yml
- .github/workflows/nightly_aws_region_cleanup.yml
- .github/workflows/scripts/c8_namespace_parser.sh
- aws/dual-region/scripts/export_environment_prerequisites.sh
- test/multi_region_aws_camunda_test.go
related to https://github.com/camunda/team-infrastructure-experience/issues/180
- finds and parses the c8 helm chart
- packageRules and customManager weren't working well together, that's why I used custom regex versioning to not bump major versions in certain files
- install tools via asdf as discussed in the team meeting
- update cloud-nuke via renovate
- run the procedure automatically for certain files but limit the execution to maximum 1 per actor
- e.g. only have one job running of renovate at a time.
- limited to also just a couple of files, we can always manually execute more if needed or add more if we see it fit
> chore(renovate): update helm chart and more dependencies

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/kubectl/helpers.go
- test/multi_region_aws_camunda_test.go
related to https://github.com/camunda/team-infrastructure-experience/issues/209
uses the oci published snapshot image for the Helm chart for the snapshot image tests.
Tested here: https://github.com/camunda/c8-multi-region/actions/runs/8891867601/job/24416132876
Generally works but due to snapshots more prone to fail, same also failed in the nightly due to Operate not starting up.
```
TestAWSDeployDualRegCamunda/TestDeployC8Helm 2024-04-30T09:17:52Z logger.go:66: - name: camunda
TestAWSDeployDualRegCamunda/TestDeployC8Helm 2024-04-30T09:17:52Z logger.go:66:   namespace: snapshot-cluster-0
TestAWSDeployDualRegCamunda/TestDeployC8Helm 2024-04-30T09:17:52Z logger.go:66:   version: 0.0.0-main-snapshot
TestAWSDeployDualRegCamunda/TestDeployC8Helm 2024-04-30T09:17:52Z logger.go:66: …
```
> chore(gha): use snapshot helm chart for snapshot tests

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/aws/helpers.go
- test/internal/helpers/kubectl/helpers.go
- test/multi_region_aws_camunda_test.go
Spot instances are causing some errors that cause too much flakiness.
Eventually environments will become healthy but it takes too much time for the tests to not fail.
It's related to volumes shifting between nodes and zones. If first deployed on zone a but then node recalled, moved to b, the switch takes too long and increasing timeouts is not gonna help.
Additionally, add some log dumps with uploads.
> chore(go): disable spot instances and add log dump

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/kubectl/helpers.go
Camunda 8.5.1 and snapshot require the presence of a csrf token.
Therefore, if the value is present add it to the request.
Additionally, small fix on the upload logs.
> chore(tests): add csrf token if available

- .github/workflows/nightly_aws_operational_procedure.yml
- test/internal/helpers/helpers.go
- test/internal/helpers/kubectl/helpers.go
- test/multi_region_aws_camunda_test.go
closes https://github.com/camunda/c8-multi-region/issues/94 https://github.com/camunda/c8-multi-region/issues/92
I used a local kind cluster to check that everything is working to the degree that it's possible.
The alpha changes on the port changes still have not been merged but I checked that the alpha chart is deployed and the tags are adjusted accordingly.
I also checked that CSRF token is used based on the implementation for this I compared 8.6.0-alpha2 (old csrf token) and SNAPSHOT with the new token. Both worked.
~A successful run remains limited by the alpha adjustments in the helm chat but at least we're prepared when it's done.~
Everything merged and working
> chore(test): adjust latest developments on alpha chart, new csrf token, and global tags

- .github/workflows/nightly_aws_operational_procedure.yml
Because now we use the directory-based structure and all chart versions in the same branch, we renamed the snapshot docker tag to match the new style.
> refactor: update helm chart alpha tag

- .github/workflows/nightly_aws_operational_procedure.yml
With the per actor concurrency check, the same actor triggering CI in two different PRs would have one cancelled in favor of the other. A side of effect of that, is the cancellation does not prevent integration of branch, the tests are just skipped.
Using the reference documentation of github for concurrency, this PR uses the github.ref as the key. The `cancel-in-progress: true` ensures that only the latest version of the commit in the CI is the choosen one.
> chore(gh workflow): concurrency key is now per branch instead of actors

- .github/workflows/nightly_aws_operational_procedure_snpashot.yml
- .github/workflows/nightly_aws_operational_procedure_stable.yml
- .github/workflows/scripts/c8_namespace_parser.sh
related to https://camunda.slack.com/archives/C076N4G1162/p1731642592303449
Quick separation of the workflows to stable and snapshot.
Each just running once a week, also allows us to mute the snapshot one afterwards.
Snapshot added condition to only run on schedule or if the branch contains required naming.
> chore: separate stable and snapshot execution

- aws/dual-region/terraform/config.tf
In the stable 8.6 branch, terraform init fails out of the box due to a conflict in aws provider versions. 
This PR changes an explicit 5.80.0 requirement to >= 5.80.0, resolving the conflict, as a different module requires >=5.81.0
> fix: change explicit aws provider version requirement to >= 5.80

- .github/workflows/reuseable_aws_operational_procedure.yml
with 8.7 and 8.8 concurrently being developed we have the issue that snapshot is 8.8 and we try to use that with 8.7 helm chart, therefore rely for now on the 8.7 related image tags defined in the helm chart
> fix: rely on helm chart tags instead of overwriting

- aws/dual-region/scripts/create_elasticsearch_secrets.sh
- aws/dual-region/scripts/generate_zeebe_helm_values.sh
- aws/dual-region/scripts/test_dns_chaining.sh
- test/internal/helpers/aws/helpers.go
- test/internal/helpers/helpers.go
- test/internal/helpers/kubectl/helpers.go
- test/multi_region_aws_camunda_test.go
- test/multi_region_aws_dns_chaining_test.go
Backporting these changes should enable teleport tests on main to keep the logic of selecting the appropriate stable branch from the helm chart version being tested. 
This is an MVP that will only support testing the new operational procedure through teleport only.
> feat: Partial backport of functions supporting teleport tests stable/8.6

- .github/workflows/nightly_teleport_operational_procedure_snapshot.yml
- .github/workflows/nightly_teleport_operational_procedure_stable.yml
For testing the automatic workflow retries, infra team's workflow re-run job needs the main branch to be updated with the required inputs first.
> feat: add extra input for the workflow dispatch trigger

- .github/workflows/nightly_aws_operational_procedure_stable.yml
- .github/workflows/nightly_teleport_operational_procedure_snapshot.yml
- .github/workflows/nightly_teleport_operational_procedure_stable.yml
- aws/dual-region/kubernetes/camunda-values.yml
- aws/dual-region/scripts/export_environment_prerequisites.sh
- test/multi_region_aws_camunda_test.go
The helm chart could not start due to duplicate entries in the resulting manifest.
The bitnami charts finally fixed a required workaround upstream.
Also bumping the 11.2.1 and stable branch to include the fix to work properly.
Related to:
* [bitnami/elasticsearch] fix: 🐛 Mount emptyDir in /bitnami/elasticsear… (#31607) ([5d7d47f](https://github.com/bitnami/charts/commit/5d7d47f34e21d61c8e117a75dcf8713554140f7b)), closes [#31607](https://github.com/bitnami/charts/issues/31607)
> fix: remove empty-dir addition since its fixed upstream

- .github/workflows/nightly_teleport_operational_procedure_snapshot.yml
- .github/workflows/reusable_teleport_operational_procedure.yml
small PR as I noticed that the `triage` triggers always.
Another point is that the branch was not used actually and it always did a checkout of something else.
Will require an adjustment in the future ... still not perfect but atm it would use `stable/8.6` properly on schedule.
> chore: fix branch usage in teleport and not waste runtime

- MAINTENANCE.md
- aws/dual-region/terraform/clusters.tf
For "next" (8.7) should switch over to the new repository.
> chore: switch module source for next version

- .github/workflows/reusable_teleport_operational_procedure.yml
- .github/workflows/reuseable_aws_operational_procedure.yml
`alpha` chart has become `8.8` and is not compatible atm.
Switching to the `8.7` snapshot.
Will merge after everything passed.
> fix: switch over to 8.7 snapshot

- aws/dual-region/kubernetes/camunda-values.yml
backport of PVC adjustments for a smoother migration as statefulsets are immutable to most parts.
1 GB for Zeebe was too little for 8.8 causing issues, therefore adjusted it for 8.7.
related to https://github.com/camunda/c8-multi-region/pull/764
we can also leave it as is in a separate branch otherwise.
> chore: increase initial pvc for smoother migration to 8.8

- .github/workflows/reusable_teleport_operational_procedure.yml
related to https://camunda.slack.com/archives/C03UR0V2R2M/p1759767263504279
Only overwrite in PRs to the head_ref if the detected minor version is contained in the base ref branch.
So in case of main, the stable checks (that the workflow structure itself works) is still using the value files of minor version branches.
In case of snapshot, we anyway overwrite it to main.
For 8.7 / 8.6 it doesn't matter too much since they can only run the with their own version anyway but can't hurt to backport as it would always match.
```
Determining the checkout info
/usr/bin/git branch --list --remote origin/stable/8.6
origin/stable/8.6
```
> fix: only use head ref in PR if base ref matches
